aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path, include
#import flower.views as flower

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flower/', include('flower.urls')),
]

aiapps/flower/urls.py
from django.urls import path

from . import views

app_name = 'flower'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

aiapps/flower/models.py
from django.db import models

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model, load_model
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from PIL import Image
import sys
import io, base64

graph = tf.compat.v1.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224
    MODEL_FILE_PATH = './flower/ml_models/vgg16_transfer.tflite'
   # MODEL_FILE_PATH = './flower/ml_models/vgg16_transfer.h5'


    classes = ["dandelion", "wood sorrel","pansy","trifolium repens","majalis","azalea","viola mandshurica","hyacinth","rhoeas","cherry blossom"]
    classes_jp = ["タンポポ", "カタバミ","パンジー","シロツメクサ","スズラン","ツツジ","スミレ","ヒヤシンス","ヒナゲシ","サクラ"]
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph
        with graph.as_default():
            #model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))

            temp_img_array=img_to_array(image)
            img=temp_img_array.astype('float32')/255.0
            img=temp_img_array.reshape((1,self.IMAGE_SIZE,self.IMAGE_SIZE,3))

            #model = load_model('./vgg16_transfer.h5')
            interpreter = tf.lite.Interpreter(model_path=self.MODEL_FILE_PATH)
            interpreter.allocate_tensors()

            # Get input and output tensors.
            input_details = interpreter.get_input_details()
            output_details = interpreter.get_output_details()

            # add N dim
            interpreter.set_tensor(input_details[0]['index'], img)
            interpreter.invoke()


            # The function `get_tensor()` returns a copy of the tensor data.
            # Use `tensor()` in order to get a pointer to the tensor.
            output_data = interpreter.get_tensor(output_details[0]['index'])
            print(output_data)

            predicted = output_data[0].argmax()
            percentage = int(output_data[0][predicted] * 100)
            #print(classes[predicted], percentage)
            return self.classes_jp[predicted], percentage



    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()
            return 'data:'+img.file.content_type+';base64,'+base64_img

aiapps/flower/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

aiapps/flower/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template('flower/index.html')
    context = {'form': PhotoForm()}
    return HttpResponse(template.render(context, request))


def predict(request):
    if not request.method == 'POST':
        return
        redirect('flower:index')

    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValuueError('Formが不正です')
    
    photo = Photo(image=form.cleaned_data['image'])
    predicted, ratio = photo.predict()

    template = loader.get_template('flower/result.html')

    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predicted,
        'ratio': ratio,
    }
    return HttpResponse(template.render(context, request))

aiapps/flower/templates/flower/base.html
<!DOCTYPE html>
<HTML lang="ja">
    <head>
        <meta chaset = "UTF-8">
        {% load bootstrap4 %}
        {% load static %} 
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'flower/css/style.css' %}">
        {% bootstrap_javascript jquery='full' %}
        <title>おはな探し | {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">画像判定AIアプリ</a>
        </nav>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</HTML>

aiapps/flower/templates/flower/index.html
{% extends 'flower/base.html' %}
{% block title %}おはな判定アプリメニュー{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">おはな判定アプリ</h4>
    <p>ファイルを選択して推定ボタンをクリックしてください</p>
    <form action="{% url 'flower:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="custom-file">
                推定したいファイルを選択してください。
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">推定する</button>
    </form>
</div>
{% endblock %}

aiapps/flower/templates/flower/result.html
{% extends 'flower/base.html' %}
{% block title %}おはな判定結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">おはな判定結果</h4>
    <table class='table'>
        <tbody>
            <tr>
                <td>画像ファイル名</td>
                <td>{{ photo_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class='view-img' width='300px' src={{ photo_data }}></img></td>
            </tr>
            <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{ ratio }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{% url 'flower:index' %}" class="btn btn-primary" >画像選択メニューに戻る</a>
</div>
{% endblock %}